export const DEMO_VENUES = [
  {
    id: 'seed-venue-pergamino',
    name: 'Pergamino Café',
    type: 'Café',
    address: 'Cra. 37 #8A-37, El Poblado, Medellín',
    openingHours: 'Lun-Sáb 7:00-21:00, Dom 9:00-18:00',
    description: 'Café de especialidad ideal para conversar sin afán.',
    commissionRate: 0.1,
    averageSpentPerPerson: 28000,
    tags: ['café', 'estudio', 'brunch'],
  },
  {
    id: 'seed-venue-velvet',
    name: 'Café Velvet',
    type: 'Café',
    address: 'Cra. 33 #7-26, El Poblado, Medellín',
    openingHours: 'Lun-Dom 8:00-22:00',
    description: 'Café tranquilo y acogedor, perfecto para una primera cita.',
    commissionRate: 0.12,
    averageSpentPerPerson: 32000,
    tags: ['café', 'lectura', 'tranquilo'],
  },
  {
    id: 'seed-venue-cine-tesoro',
    name: 'Cine Colombia El Tesoro',
    type: 'Cine',
    address: 'CC El Tesoro, Cra. 25A #1A Sur-45, El Poblado, Medellín',
    openingHours: 'Lun-Dom 12:00-22:00',
    description: 'Salas de cine para ver el estreno del momento.',
    commissionRate: 0.08,
    averageSpentPerPerson: 30000,
    tags: ['cine', 'películas', 'palomitas'],
  },
  {
    id: 'seed-venue-crepes',
    name: 'Crepes & Waffles Las Vegas',
    type: 'Restaurante',
    address: 'Av. Las Vegas #2 Sur-72, El Poblado, Medellín',
    openingHours: 'Lun-Dom 12:00-22:00',
    description: 'Crepes dulces y saladas en un ambiente relajado.',
    commissionRate: 0.1,
    averageSpentPerPerson: 40000,
    tags: ['comida', 'postres', 'cena'],
  },
  {
    id: 'seed-venue-presidenta',
    name: 'Parque de la Presidenta',
    type: 'Parque',
    address: 'Cra. 43A con Cl. 11A, El Poblado, Medellín',
    openingHours: 'Lun-Dom 6:00-18:00',
    description: 'Parque al aire libre para caminar y compartir un picnic.',
    commissionRate: 0,
    averageSpentPerPerson: 15000,
    tags: ['naturaleza', 'aire libre', 'picnic'],
  },
];
